# Generated by Django 3.2.5 on 2024-02-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outdepotvehiclereceive',
            name='new_log_sheet_no',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
