# Generated by Django 3.2.5 on 2024-02-17 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_auto_20240217_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busesonhand',
            name='special_bus_data_entry',
        ),
    ]
