# Generated by Django 3.2.5 on 2024-02-17 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_remove_busesonhand_special_bus_data_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='busesonhand',
            name='bus_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buses_on_hand_vehicle', to='app.vehicledetails'),
        ),
    ]
